# Generated by Django 5.1.4 on 2025-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
