# Generated by Django 5.1.4 on 2025-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlist',
            name='is_verified',
            field=models.CharField(blank=True, default=False, max_length=10),
        ),
    ]
