# Generated by Django 5.1.4 on 2025-01-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0002_alter_devlist_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlist',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
