# Generated by Django 5.1.4 on 2025-02-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0002_quizcategory_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question', models.CharField(blank=True, max_length=255, null=True)),
                ('quiz_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.quizcategory')),
            ],
        ),
    ]
