# Generated by Django 5.1.4 on 2025-01-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0003_alter_devlist_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_summary', models.CharField(max_length=70)),
                ('bio_detail', models.CharField(max_length=70)),
                ('experties', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=20)),
                ('dev_img', models.FileField(upload_to='developer_images/')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.devlist')),
            ],
        ),
    ]
