# Generated by Django 5.1.4 on 2025-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_quizoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='is_option_added',
            field=models.BooleanField(default=False),
        ),
    ]
