# Generated by Django 5.1.4 on 2025-01-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0004_devbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devbio',
            name='bio_detail',
            field=models.TextField(max_length=255),
        ),
    ]
