# Generated by Django 5.1.4 on 2025-02-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0005_quizquestions_is_option_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='is_option_added',
        ),
    ]
