# Generated by Django 5.1.4 on 2025-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0006_remove_quizquestions_is_option_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='is_option_addded',
            field=models.BooleanField(default=False),
        ),
    ]
