# Generated by Django 5.1.4 on 2025-02-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0007_quizquestions_is_option_addded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='is_option_addded',
            new_name='is_option_added',
        ),
    ]
