# Generated by Django 5.1.4 on 2025-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0008_rename_is_option_addded_quizquestions_is_option_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='quiz_question_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
