# Generated by Django 5.1.4 on 2025-02-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0012_shortlisting_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortlisting',
        ),
    ]
