# Generated by Django 5.1.4 on 2025-02-27 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0013_delete_shortlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Certification_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(blank=True, max_length=255, null=True)),
                ('course_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
