# Generated by Django 5.1.4 on 2025-03-01 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0016_module_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Module_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_documentation', models.TextField(blank=True, null=True)),
                ('course_pdf', models.FileField(blank=True, null=True, upload_to='course_pdf/')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course_video/')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.module_stage')),
            ],
        ),
    ]
