# Generated by Django 5.1.4 on 2025-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0017_course_module_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_module_content',
            name='course_images',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
