# Generated by Django 5.1.4 on 2025-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0018_course_module_content_course_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_certification_course',
            name='course_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online_certification_course',
            name='course_thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to='course_thumbnail_images/'),
        ),
    ]
