# Generated by Django 5.1.4 on 2025-03-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0020_online_certification_course_is_launched'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='is_course_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
