# Generated by Django 5.1.4 on 2025-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0022_course_module_content_course_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.FileField(upload_to='company_logo/')),
                ('dev_signature', models.FileField(upload_to='dev_signature/')),
            ],
        ),
    ]
