# Generated by Django 5.1.4 on 2025-03-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0027_certificate_details_name_on_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate_details',
            name='name_on_certificate',
        ),
    ]
