# Generated by Django 5.1.4 on 2025-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=70)),
                ('last_sem_marksheet', models.FileField(upload_to='student_marksheet/')),
                ('student_resume', models.FileField(upload_to='student_resume/')),
                ('course', models.CharField(default='B.C.A', max_length=20)),
            ],
        ),
    ]
