# Generated by Django 5.1.4 on 2025-02-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=20),
        ),
    ]
