# Generated by Django 5.1.4 on 2025-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_user_bio_detail_user_bio_title_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
