# Generated by Django 5.1.4 on 2025-02-18 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0008_rename_is_option_addded_quizquestions_is_option_added'),
        ('studentapp', '0004_alter_user_bio_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('quiz_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devapp.quizcategory')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
