# Generated by Django 5.1.4 on 2025-02-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_quiz_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_attempt',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='quiz_attempt',
            name='quiz_category',
        ),
        migrations.RemoveField(
            model_name='quiz_attempt',
            name='student_id',
        ),
    ]
