# Generated by Django 5.1.4 on 2025-02-18 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0008_rename_is_option_addded_quizquestions_is_option_added'),
        ('studentapp', '0006_remove_quiz_attempt_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_attempt',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz_attempt',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.quizcategory'),
        ),
        migrations.AddField(
            model_name='quiz_attempt',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
