# Generated by Django 5.1.4 on 2025-02-24 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0010_online_sessions'),
        ('studentapp', '0007_quiz_attempt_date_time_quiz_attempt_quiz_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempted_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_attempted', models.BooleanField(default=False)),
                ('session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.online_sessions')),
                ('student_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
