# Generated by Django 5.1.4 on 2025-03-06 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0022_course_module_content_course_quiz'),
        ('studentapp', '0010_user_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_received', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.online_certification_course')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
