# Generated by Django 5.1.4 on 2025-03-06 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0022_course_module_content_course_quiz'),
        ('studentapp', '0012_course_progress_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_progress_tracker',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.quizcategory'),
        ),
    ]
