# Generated by Django 5.1.4 on 2025-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0013_course_progress_tracker_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrollment',
            name='is_course_completed',
            field=models.BooleanField(default=False),
        ),
    ]
