# Generated by Django 5.1.4 on 2025-03-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0015_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
