# Generated by Django 5.1.4 on 2025-03-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0016_rename_student_id_contact_us_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
