# Generated by Django 5.1.4 on 2025-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course_query',
            name='query_status',
            field=models.BooleanField(default=False),
        ),
    ]
