# Generated by Django 5.1.4 on 2025-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0020_student_course_query_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_img',
            field=models.FileField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
